# -*- coding: utf-8 -*-
"""datasciencesalary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r3P7oMflx06g-lRopvINpJQ0cgrM9VdO
"""



import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer  
#TfidfVectorizer #basic idea to take  the text 
#and convert it to something that can be feaded to ML model


# "TF matrix : tearm frequency" and "IDF matrix : Inverse document frequency"

from sklearn.svm import LinearSVC


data = pd.read_csv("/content/drive/MyDrive/ds_salaries.csv")
x, y = data['job_title'],data['salary']
x_train, x_test ,y_train, y_test = train_test_split(x,y,test_size=0.2)

vectorizer = TfidfVectorizer(stop_words="english",max_df=0.7)
x_train_vectorize = vectorizer.fit_transform(x_train)
x_test_vectorize = vectorizer.transform(x_test)


clf = LinearSVC()
clf.fit(x_train_vectorize,y_train)
clf.score(x_test_vectorize, y_test)

text = "ML Engineer"

vectorize_text = vectorizer.transform([text])
clf.predict(vectorize_text)

from google.colab import drive
drive.mount('/content/drive')